services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=user
      - MARIADB_DATABASE=database
      - MARIADB_PASSWORD=password
    ports:
      - 3306:3306
  myapp:
    image: bitnami/laravel:latest
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=user
      - DB_DATABASE=database
      - DB_PASSWORD=password
    depends_on:
      - mariadb
    ports:
      - 8000:8000
    volumes:
      - ./my-project:/app